version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    command: serve
    restart: unless-stopped

  watcher:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../data:/app/data
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    command: watch
    restart: unless-stopped